apiVersion: v1
kind: Pod
metadata:
 name: web
 labels:
  name: mongodb
  tier: db
spec:
 containers:
 - name: web
   imagePullPolicy: Always
   image: techworldwithsiva/mongodb:v1
   
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
     name: mongodb
     tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
    


