
  
    
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
   MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-mysecret
  type: Opaque
data:
  username: c2hpcHBpbmc=

  password: c2VjcmV0


---
apiVersion: v1
kind: Pod
metadata:
 name: mysql
 labels:
  name: mysql
  tier: db
spec:
 containers:
 - name: web
   imagePullPolicy: Always
   image: suresh090/mysql:k8
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretKeyRef: 
        name: mysql-mysecret
   ports:
    - containerPort: 3306
    
   
   
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
     name: mysql
     tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
    


